# service1.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service1
  description: Example microservice
  annotations:
    github.com/project-slug: org/service1
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - spring
    - microservice
  links:
    - url: https://jenkins.example.com/job/service1
      title: Jenkins Pipeline
      icon: jenkins
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: payment-system
  dependsOn:
    - component:default/service2
    - resource:default/payment-db
---
# service2.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service2
  description: Authentication Service
  annotations:
    github.com/project-slug: org/service2
  tags:
    - nodejs
    - auth
spec:
  type: service
  lifecycle: production
  owner: team-b
  system: auth-system
  providesApis:
    - auth-api
---
# api.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: Authentication API
spec:
  type: openapi
  lifecycle: production
  owner: team-b
  definition:
    $text: https://github.com/org/service2/blob/main/api-spec.yaml
---
# resource.yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: payment-db
  description: Payment Database
spec:
  type: database
  owner: team-a
  system: payment-system
---
# systems.yaml
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: payment-system
  description: Payment Processing System
spec:
  owner: team-a
  domain: payments
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: auth-system
  description: Authentication System
spec:
  owner: team-b
  domain: security
---
# domains.yaml
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: payments
  description: Payments Domain
spec:
  owner: team-a
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: security
  description: Security Domain
spec:
  owner: team-b
---
# groups.yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Payment Team
spec:
  type: team
  profile:
    displayName: Team A
    email: team-a@example.com
  parent: engineering
  children: []
  members:
    - user1
    - user2
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-b
  description: Security Team
spec:
  type: team
  profile:
    displayName: Team B
    email: team-b@example.com
  parent: engineering
  children: []
  members:
    - user3
    - user4
---
# users.yaml
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user1
spec:
  profile:
    displayName: John Doe
    email: john@example.com
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user2
spec:
  profile:
    displayName: Jane Smith
    email: jane@example.com
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user3
spec:
  profile:
    displayName: Bob Wilson
    email: bob@example.com
  memberOf: [team-b]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user4
spec:
  profile:
    displayName: Alice Brown
    email: alice@example.com
  memberOf: [team-b]
